### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by wcwq98** [zzseki/QChatGPT_Plugin_Weather#1]
因为无法使用bot安装，所以便想着手动安装
但安装好了但好像运行不起来
 日志：root@hcss-ecs-bae2:~/QChatGPT/plugins/QChatGPT_Plugin_Weather# python main.py
Traceback (most recent call last):
  File "/root/QChatGPT/plugins/QChatGPT_Plugin_Weather/main.py", line 1, in <module>
    from pkg.plugin.context import (
ModuleNotFoundError: No module named 'pkg'

**Comment by zzseki** [comment]
可能是项目路径有关的问题，最好还是使用bot安装吧，bot安装是什么问题呢

**Comment by wcwq98** [comment]
一直显示这个[bot] 插件安装失败: 'NoneType' object is not subscriptable

**Comment by zzseki** [comment]
这个感觉不像插件的问题，建议去qchatgpt的qq群里去问问，有没有安装过别的插件呢，会不会有同样的问题？

**Comment by wcwq98** [comment]
音乐那个能安装但是天气就安装不了  还有顺便问下去哪搞网易云的cookie

**Comment by zzseki** [comment]
我刚刚试了一下，我是可以安装这个插件的，会不会是适配器的问题或者给我看看你的控制台
